Repository tenstorrent/tt-forge-fe, pull requests merged in 2024-11, with the labels that each got.

#382 Forge tests for Matmul operator
  forge/test/operators/pytorch/matmul/__init__.py
  forge/test/operators/pytorch/matmul/test_matmul.py
  forge/test/operators/utils/pytest.py
  forge/test/operators/utils/utils.py
Labels: Ops

#329 Forge tests for Softmax operator
  forge/test/operators/pytorch/nn/__init__.py
  forge/test/operators/pytorch/nn/conftest.py
  forge/test/operators/pytorch/nn/test_command.sh
  forge/test/operators/pytorch/nn/test_softmax.py
Labels: Ops

#423 Forge tests for PyTorch unary operators
  forge/test/operators/pytorch/eltwise_unary/__init__.py
  forge/test/operators/pytorch/eltwise_unary/test_unary.py
  forge/test/operators/utils/failing_reasons.py
Labels: Ops

#240 Test torch binary operators
  forge/test/operators/pytorch/eltwise_binary/__init__.py
  forge/test/operators/pytorch/eltwise_binary/failing_rules.py
  forge/test/operators/pytorch/eltwise_binary/test_binary.py
  forge/test/operators/pytorch/test_inconsistency.py
  forge/test/operators/utils/failing_reasons.py
  forge/test/operators/utils/test_data.py
Labels: Ops

#620 Test new binary operators
  forge/test/operators/pytorch/eltwise_binary/failing_rules.py
  forge/test/operators/pytorch/eltwise_binary/test_binary.py
  forge/test/operators/utils/failing_reasons.py
Labels: Ops

#664 fix shape attribute issue in reshape op in hoist_unsqueeze_squeeze_to_reshape
  forge/csrc/passes/explicate_unsqueeze.cpp
  forge/test/mlir/test_ops.py
  forge/test/model_demos/high_prio/cnn/pytorch/test_rcnn.py
  forge/test/model_demos/high_prio/cnn/pytorch/test_vgg.py
Labels: bug

#556 Tests for concatenate op
  forge/test/operators/pytorch/eltwise_nary/__init__.py
  forge/test/operators/pytorch/eltwise_nary/test_concatenate.py
  forge/test/operators/utils/failing_reasons.py
  forge/test/operators/utils/plan.py
Labels: Ops

#380 Kmilanovic/pytorch reduce ops tests
  forge/test/operators/pytorch/reduce/__init__.py
  forge/test/operators/pytorch/reduce/errors/test_reduce_ids_failed_mlir_verif_error.txt
  forge/test/operators/pytorch/reduce/errors/test_reduce_ids_pcc_error.txt
  forge/test/operators/pytorch/reduce/errors/test_reduce_ids_tilize_dtype_error.txt
  forge/test/operators/pytorch/reduce/errors/test_reduce_ids_tilize_error.txt
  forge/test/operators/pytorch/reduce/errors/test_reduce_ids_unsupported_dim_error.txt
  forge/test/operators/pytorch/reduce/test_reduce.py
  forge/test/operators/utils/failing_reasons.py
Labels: Ops

#747 Nightly_sweeps pytest mark for nightly CI run
  forge/test/operators/pytorch/matmul/test_matmul.py
  forge/test/operators/pytorch/nn/test_softmax.py
  forge/test/operators/pytorch/test_all.py
  pytest.ini
Labels: Ops, CI / Infra

#789 Run nightly-sweeps tests on schedule
  .github/workflows/build-and-test.yml
  .github/workflows/on-nightly-sweeps.yml
Labels: Ops, CI / Infra

#740 Remove leftover hslice, vslice, hstack and vstack
  forge/csrc/forge_passes.cpp
  forge/csrc/graph_lib/utils.cpp
  forge/csrc/graph_lib/utils.hpp
  forge/csrc/passes/fracture.cpp
  forge/csrc/passes/fuse_redundant_tm_sequence.hpp
  forge/csrc/passes/link_past_cache_ios.cpp
  forge/csrc/passes/move_select_after_matmul_optional.cpp
  forge/csrc/passes/move_select_after_matmul_optional.hpp
  forge/csrc/passes/passes_utils.cpp
  forge/csrc/passes/pre_placer_forge_passes.cpp
  forge/csrc/passes/pre_placer_forge_passes.hpp
  forge/csrc/test/graph_lib/test_graphlib_utils.cpp
  forge/csrc/test/passes/test_fracturing.cpp
  forge/csrc/test/passes/test_move_select_after_matmul_optional.cpp
  forge/forge/op/__init__.py
  forge/forge/op/eval/forge/tm.py
  forge/forge/op/tm.py
Labels: tech-debt
