Repository tenstorrent/tt-forge-fe, pull requests merged in 2024-12, with the labels that each got.

#904 update requirements
  env/core_requirements.txt
  env/linux_requirements.txt
  env/mac_requirements.txt
Labels: Model Bringup

#926 Resolve issues with specific ops
  forge/test/mlir/llama/tests/test_specific_ops_llama32.py
Labels: Ops

#948 Add HF_TOKEN to workflow
  .github/workflows/build-and-test.yml
  forge/test/mlir/llama/test_llama_inference.py
  forge/test/mlir/llama/tests/test_llama_embedding.py
  forge/test/mlir/llama/tests/test_llama_lm_head.py
  forge/test/mlir/llama/tests/test_llama_mlp.py
  forge/test/mlir/llama/tests/test_llama_prefil.py
  forge/test/mlir/llama/tests/test_llama_rms_norm.py
  forge/test/mlir/llama/tests/test_llama_rotary_emb.py
  forge/test/mlir/llama/tests/test_llama_self_attn.py
Labels: CI / Infra

#711 Tests for transpose op
  forge/test/operators/pytorch/tm/__init__.py
  forge/test/operators/pytorch/tm/test_transpose.py
  forge/test/operators/utils/failing_reasons.py
Labels: Ops
