Repository tenstorrent/tt-forge-fe, pull requests merged in 2025-01, with the labels that each got.

#1011 Update model analysis docs
  model_analysis_docs/Models/albert/pt_albert_base_v1_masked_lm.md
  model_analysis_docs/Models/albert/pt_albert_base_v1_token_cls.md
  model_analysis_docs/Models/albert/pt_albert_base_v2_masked_lm.md
  model_analysis_docs/Models/albert/pt_albert_base_v2_token_cls.md
  model_analysis_docs/Models/bert/pt_bert_masked_lm.md
  model_analysis_docs/Models/densenet/pt_densenet_161.md
  model_analysis_docs/Models/distilbert/pt_distilbert_masked_lm.md
  model_analysis_docs/Models/distilbert/pt_distilbert_sequence_classification.md
  model_analysis_docs/Models/distilbert/pt_distilbert_token_classification.md
  model_analysis_docs/Models/dpr/pt_dpr_ctx_encoder_multiset_base.md
  model_analysis_docs/Models/dpr/pt_dpr_ctx_encoder_single_nq_base.md
  model_analysis_docs/Models/dpr/pt_dpr_question_encoder_multiset_base.md
  model_analysis_docs/Models/dpr/pt_dpr_question_encoder_single_nq_base.md
  model_analysis_docs/Models/dpr/pt_dpr_reader_multiset_base.md
  model_analysis_docs/Models/dpr/pt_dpr_reader_single_nq_base.md
  model_analysis_docs/Models/llama3/pt_Llama_3_2_1B_Instruct_seq_cls.md
  model_analysis_docs/Models/llama3/pt_Llama_3_2_1B_seq_cls.md
  model_analysis_docs/Models/mlp_mixer/pt_mixer_s16_224.md
  model_analysis_docs/Models/mlp_mixer/pt_mixer_s32_224.md
  model_analysis_docs/Models/opt/pt_opt_125m_qa.md
  model_analysis_docs/Models/opt/pt_opt_125m_seq_cls.md
  model_analysis_docs/Models/phi2/pt_phi_2_pytdml_seq_cls.md
  model_analysis_docs/Models/phi2/pt_phi_2_pytdml_token_cls.md
  model_analysis_docs/Models/phi2/pt_phi_2_seq_cls.md
  model_analysis_docs/Models/phi2/pt_phi_2_token_cls.md
  model_analysis_docs/Models/qwen_coder/pt_Qwen_Qwen2_5_Coder_0_5B.md
  model_analysis_docs/Models/roberta/pt_roberta_masked_lm.md
  model_analysis_docs/Models/roberta/pt_roberta_sentiment.md
  model_analysis_docs/Models/segformer/pt_mit_b1.md
  model_analysis_docs/Models/segformer/pt_mit_b2.md
  model_analysis_docs/Models/segformer/pt_mit_b3.md
  model_analysis_docs/Models/segformer/pt_mit_b4.md
  model_analysis_docs/Models/segformer/pt_mit_b5.md
  model_analysis_docs/Models/stereo/pt_musicgen_large.md
  model_analysis_docs/Models/stereo/pt_musicgen_medium.md
  model_analysis_docs/Models/stereo/pt_musicgen_small.md
  model_analysis_docs/Models/swin/pt_swinv2_tiny_patch4_window8_256.md
  model_analysis_docs/Models/t5/pt_google_flan_t5_base.md
  model_analysis_docs/Models/t5/pt_google_flan_t5_small.md
  model_analysis_docs/Models/t5/pt_t5_base.md
  model_analysis_docs/Models/t5/pt_t5_large.md
  model_analysis_docs/Models/t5/pt_t5_small.md
  model_analysis_docs/Models/vovnet/pt_vovnet27s.md
  model_analysis_docs/ModelsInfo.md
Labels: automatic_model_analysis

#951 update test.md docs
  docs/src/SUMMARY.md
  docs/src/pytest.md
Labels: documentation

#862 Reshape operator test
  forge/test/operators/pytorch/eltwise_unary/__init__.py
  forge/test/operators/pytorch/eltwise_unary/models.py
  forge/test/operators/pytorch/eltwise_unary/test_unary.py
  forge/test/operators/pytorch/tm/test_reshape.py
  forge/test/operators/pytorch/tm/test_reshape_ids_failed_allclose_value_checker.txt
  forge/test/operators/utils/compat.py
  forge/test/operators/utils/failing_reasons.py
  forge/test/operators/utils/utils.py
Labels: Ops

#960 Documentation for verify()
  docs/src/SUMMARY.md
  docs/src/dev_notes/verification.md
  docs/src/imgs/checkers/checkers.svg
  docs/src/imgs/checkers/value_checkers.excalidraw
Labels: documentation

#941 Support value range for tensors with default df
  forge/test/operators/pytorch/eltwise_binary/test_binary.py
  forge/test/operators/pytorch/eltwise_unary/test_unary.py
  forge/test/operators/pytorch/matmul/test_matmul.py
  forge/test/operators/pytorch/nn/test_softmax.py
  forge/test/operators/utils/compat.py
Labels: bug

#1085 Improve test id parsing
  forge/test/operators/utils/plan.py
Labels: bug

#962 Squeeze pytorch operator test plan
  forge/test/operators/pytorch/tm/test_squeeze.py
Labels: Ops

#986 Unsqueeze pytorch operator test plan
  forge/test/operators/pytorch/tm/test_unsqueeze.py
Labels: Ops

#1117 Add Attribute Name and Type Mapping System
  forge/csrc/passes/lower_to_mlir.cpp
Labels: enhancement

#1118 Add repeat_interleave Op
  forge/csrc/passes/lower_to_mlir.cpp
  forge/test/mlir/llama/test_llama_inference.py
  forge/test/mlir/llama/tests/test_llama_self_attn.py
  forge/test/mlir/llama/tests/test_specific_ops_llama32.py
  forge/test/mlir/operators/tm/test_tm.py
Labels: Ops, Model Bringup
