Repository tenstorrent/tt-forge-fe, pull requests merged in 2025-02, with the labels that each got.

#1143 Change embedding backward op output data format setup
  forge/csrc/autograd/python_bindings.cpp
  forge/forge/op/eval/forge/embedding.py
Labels: bug

#1183 Update nightly sweeps github action
  .github/workflows/on-nightly-sweeps.yml
Labels: CI / Infra

#1098 Restore default value range behavior for reduce ops
  forge/test/operators/pytorch/reduce/test_reduce.py
Labels: bug

#1195 Adapt to removal of global compiler config in sweep tests
  forge/test/operators/utils/compat.py
  forge/test/operators/utils/utils.py
Labels: tech-debt

#1040 Repeat_interleave operator test plan & failing rules
  forge/test/operators/pytorch/tm/test_repeat_interleave.py
  forge/test/operators/utils/failing_reasons.py
Labels: Ops

#1197 Fix parsing math fidelity
  forge/test/operators/utils/plan.py
Labels: bug

#1212 Fix collecting operator index in test suite
  forge/test/operators/pytorch/test_all.py
  forge/test/operators/utils/plan.py
Labels: bug

#1189 Unsqueeze operator test failing rules
  forge/test/operators/pytorch/tm/test_unsqueeze.py
Labels: Ops

#1041 Add Max operator test plan
  forge/test/operators/pytorch/reduce/test_max.py
Labels: Ops

#1124 Reshape operator failing rules
  forge/test/operators/pytorch/tm/test_reshape.py
  forge/test/operators/pytorch/tm/test_reshape_ids_failed_allclose_value_checker.txt
  forge/test/operators/utils/failing_reasons.py
Labels: Ops

#1131 Squeeze operator tests failing rules
  forge/test/operators/pytorch/tm/test_squeeze.py
  forge/test/operators/pytorch/tm/test_squeeze_ids_failed_allclose_value_checker.txt
  forge/test/operators/utils/failing_reasons.py
Labels: Ops

#965 Tests for linear op
  forge/test/operators/pytorch/nn/test_linear.py
  forge/test/operators/utils/failing_reasons.py
Labels: Ops, sweeps_task

#903 Test for embedding op
  forge/test/operators/pytorch/nn/test_embedding.py
  forge/test/operators/utils/failing_reasons.py
  forge/test/operators/utils/plan.py
Labels: Ops

#1203 Add 'gelu' and 'leaky_relu' operators test_plan and failing_rules
  forge/test/operators/pytorch/eltwise_unary/test_unary.py
  forge/test/operators/utils/__init__.py
  forge/test/operators/utils/utils.py
Labels: Ops

#1224 Cumsum operator TestPlan&FailingRules
  forge/forge/op_repo/pytorch_operators.py
  forge/test/operators/pytorch/eltwise_unary/test_cumsum_ids_failed_automatic_value_checker.txt
  forge/test/operators/pytorch/eltwise_unary/test_unary.py
Labels: Ops
