Repository tenstorrent/tt-forge-fe, pull requests merged in 2025-03, with the labels that each got.

#1402 Filtering tests by operator
  .github/workflows/on-nightly-sweeps.yml
  .github/workflows/test.yml
Labels: CI / Infra

#1428 Requires runs-on for nightly sweeps action
  .github/workflows/on-nightly-sweeps.yml
Labels: bug, CI / Infra

#1447 Fix naming for RUNS_ON_DEFAULT
  .github/workflows/on-nightly-sweeps.yml
Labels: bug, CI / Infra

#1252 Layernorm operator test plan
  forge/test/operators/pytorch/tm/test_layernorm.py
Labels: Ops

#1360 Softmax operator - switch to use test plan
  forge/forge/op_repo/pytorch_operators.py
  forge/test/operators/pytorch/nn/test_softmax.py
  forge/test/operators/pytorch/nn/test_softmax_ids_failed_allclose_value_checker.txt
  forge/test/operators/utils/failing_reasons.py
  forge/test/operators/utils/plan.py
Labels: Ops
