Repository tenstorrent/tt-forge-fe, pull requests merged in 2025-04, with the labels that each got.

#1432 Matmul operator - switch to use test plan
  forge/test/operators/pytorch/eltwise_binary/__init__.py
  forge/test/operators/pytorch/matmul/test_matmul.py
  forge/test/operators/pytorch/matmul/test_matmul_ids_failed_allclose_value_checker.txt
  forge/test/operators/utils/failing_reasons.py
  forge/test/operators/utils/plan.py
Labels: Ops

#1677 Fix build-if-neccessary job for nightly xfail
  .github/workflows/on-nightly-xfail.yml
Labels: bug

#1687 Revert "Fix build-if-neccessary job for nightly xfail (#1677)"
  .github/workflows/on-nightly-xfail.yml
Labels: bug, CI / Infra

#1770 All op naming convention
  forge/forge/op_repo/pytorch_operators.py
  forge/test/operators/pytorch/eltwise_binary/test_binary.py
  forge/test/operators/pytorch/eltwise_nary/test_concatenate.py
  forge/test/operators/pytorch/eltwise_unary/test_unary.py
  forge/test/operators/pytorch/matmul/test_matmul.py
  forge/test/operators/pytorch/nn/test_conv2d.py
  forge/test/operators/pytorch/nn/test_conv2d_ids_failed_inference_froze.txt
  forge/test/operators/pytorch/nn/test_embedding.py
  forge/test/operators/pytorch/nn/test_linear.py
  forge/test/operators/pytorch/nn/test_softmax.py
  forge/test/operators/pytorch/reduce/test_max.py
  forge/test/operators/pytorch/reduce/test_reduce.py
  forge/test/operators/pytorch/tm/test_layernorm.py
  forge/test/operators/pytorch/tm/test_repeat_interleave.py
  forge/test/operators/pytorch/tm/test_reshape.py
  forge/test/operators/pytorch/tm/test_squeeze.py
  forge/test/operators/pytorch/tm/test_transpose.py
  forge/test/operators/pytorch/tm/test_unsqueeze.py
  forge/test/operators/utils/utils.py
Labels: Ops

#1779 Unary ops bug fix
  forge/test/operators/pytorch/eltwise_unary/test_unary.py
Labels: Ops

#1831 Fix build when using clang18 as compiler
  CMakeLists.txt
  forge/csrc/graph_lib/query.hpp
  forge/csrc/lower_to_forge/common.hpp
  forge/csrc/shared_utils/pretty_table.cpp
Labels: community
