Repository tenstorrent/tt-forge-fe, pull requests merged in 2025-06, with the labels that each got.

#2177 Save inputs for test workflow
  .github/workflows/test.yml
Labels: CI / Infra

#2248 Update test durations based on latest nightly 2025-06-10
  .test_durations
Labels: tooling

#2331 [Bug Fix] Qwen models - removed attention_mask from the input
  forge/test/models/pytorch/text/qwen/test_qwen.py
  forge/test/models/pytorch/text/qwen/test_qwen_coder.py
  forge/test/models/pytorch/text/qwen/test_qwen_v2.py
Labels: bug

#2260 Pytorch softmax op new verification
  forge/test/operators/pytorch/ids/failing_reasons_register.py
  forge/test/operators/pytorch/ids/xfail/softmax_compilation_failed.txt
  forge/test/operators/pytorch/ids/xfail/softmax_data_mismatch.txt
  forge/test/operators/pytorch/ids/xfail/softmax_special_values.txt
  forge/test/operators/pytorch/ids/xfail/softmax_unsupported_axis.txt
  forge/test/operators/pytorch/ids/xfail/softmax_unsupported_data_format.txt
  forge/test/operators/pytorch/nn/test_softmax.py
  forge/test/operators/utils/failing_reasons.py
Labels: Ops
